<!-- 错误一定会发生
当 JavaScript 引擎执行 JavaScript 代码时，会发生各种错误。
当错误发生时，JavaScript 引擎通常会停止，并生成一个错误消息。
描述这种情况的技术术语是：JavaScript 将抛出一个错误。
-->
<!DOCTYPE html>
<html>
	<head>
		<script>
			var txt = "";
			/*
			JavaScript 错误测试和捕捉：
			try 语句定义在执行时进行错误测试的代码块。
			catch 语句定义当 try 代码块发生错误时，所执行的代码块。
			try 和 catch 总是成对出现的。
			*/
			function message() {
				try {
					adddlert("Welcome guest!");// 故意写错 alert 
				} catch(err) {// catch 块会捕捉到 try 块中的错误，并执行代码来处理它。
					txt = "本页有一个错误。\n\n";
					txt += "错误描述：" + err.message + "\n\n";
					txt += "点击确定继续。\n\n";
					alert(txt);
				}
			}
		</script>
	</head>
	<body>
		<input type="button" value="查看消息" onclick="message()" />
	</body>

</html>